### PR TITLE
three important stack question has been added!

### PR DESCRIPTION
**Pull request by Saikat2407**
Leetcode question added! #44

### CODE REVIEW

**Comment by rohan472000** [comment]
While raising your PR, a template appeared, kindly fill that one first, it contains some checkboxes, finish them and tick accordingly

**Comment by Saikat2407** [comment]
sure @rohan472000 hacktoberfest is not accepting this PR can you add hacktoberfest-accepted lebel to this PR?

**Comment by Saikat2407** [comment]
Issues checked and completed , kindly merge !! @rohan472000

**Comment by rohan472000** [comment]
> While raising your PR, a template had appeared, kindly fill that one first, it contains some checkboxes, finish them and tick accordingly

Why not this????

**Comment by Saikat2407** [comment]
Its not showing me now!

**Comment by rohan472000** [comment]
Copy PR_template.md from .github/workflows and paste it there above.

**Pull request closed without merging**
