### PR TITLE
exponential search

### PR DESCRIPTION
**Pull request by sreshtech**
### Description
Exponential Search Description :it is a searching algorithm that is used to find a specific element
within a sorted array or list. It works by first identifying a range in which the target element is likely to be located
and then performing a binary search within that range.
Exponential search is particularly useful when dealing with very large data sets or
when the target element is far from the beginning of the array.

### wiki link
https://en.wikipedia.org/wiki/Exponential_search

### Changes Made
added a new search algorithm .

### Screenshots (if applicable)
[Include any relevant screenshots or images here.]

- [x] Fixed Bug/issues
- [x] Added algo/questions_answers/docs
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by rohan472000** [comment]
Why u r deleting existing shell sort??

**Comment by sreshtech** [comment]
i only want to merge exponential search algorithm.no deletion of any other algorithm.i am not familiar with how to cancel PR for shell sort . please help.

**Comment by sreshtech** [comment]
if This pull request meets the Hacktoberfest eligibility criteria and is open for contributions. Could you please consider adding the Hacktoberfest label to this pull request as well?

Thank you for your support

**Comment by sreshtech** [comment]
can you please also assigne me this?

**Comment by rohan472000** [comment]
> can you please also assign me this?

what assign?

**Comment by sreshtech** [comment]
> > can you please also assign me this?
> 
> what assign?

Hactoberfest is not accepting this exponential search PR as it was not assigned to me.

**Comment by rohan472000** [comment]
Actually hacktoberfest wasn't accepting PR of this repo from last 4 days, so I removed it.

**Pull request merged**
