### PR TITLE
To find maximum subarray in case of all negative numbers  intialize c…

### PR DESCRIPTION
**Pull request by vaishnavin01**
…s and ms with index 0

### Description
[In this  "Kadane's  algorithm I intialize currentsum and maximum sum with index 0 element instead of zero because whenever we start with 0 in might be wrong for some cases like whenever all elements of array is negative then we get wrong answer so this issue fixed by intialize sum with index 0]

### Related/Fixes Issue
[arr={-1,-1}]

### Changes Made
[cs=nums[0]
ms=nums[0]]

### Screenshots (if applicable)
[Include any relevant screenshots or images here.]

- [x] Fixed Bug/issues
- [x] Added algo/questions_answers/docs
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by vaishnavin01** [comment]
Iwould like to work on this algorithm.

**Review by rohan472000 — CHANGES_REQUESTED** [review]
Also put this .java file  in appropriate folder.

**Comment by vaishnavin01** [comment]
can I create new folder for Array because it is Arraybased problem

**Comment by rohan472000** [comment]
> can I create new folder for Array because it is Arraybased problem

Ya sure

**Comment by vaishnavin01** [comment]
i changed this cadanes algorithm because it is more efficient and readable when we created a specific function for perticular problem and algorithm which is written previously is not correct for arra which contens all negative elements it gives output 0 which is incorrect

**Comment by rohan472000** [comment]
Well kadane algo and Max subarray is two different things , so better keep it separate.

**Comment by vaishnavin01** [comment]
Now its ok

**Pull request closed without merging**
