### PR TITLE
Added Sudoku.java

### PR DESCRIPTION
**Pull request by Abdul-Azeez060**
### Description
I have added backtracking folder and in that I have added sudoku.java file

### Related/Fixes Issue
[Reference the related issue or task using its number or link.]

### Changes Made
[Briefly list the specific code changes made.]

### Screenshots (if applicable)
[Include any relevant screenshots or images here.]

- [x] Fixed Bug/issues
- [x] Added algo/questions_answers/docs
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by Abdul-Azeez060** [comment]
Hey don't forget to add the hactoberfest-accepted label

**Comment by rohan472000** [comment]
First tick the checkboxes correctly in PR description.

**Comment by Abdul-Azeez060** [comment]
done

**Review by rohan472000 — COMMENTED** [review]
don't give that much long description, make it small and concise.

**Pull request closed without merging**
