### PR TITLE
Adding important graph algos inside Graphs folder

### PR DESCRIPTION
**Pull request by madm234**
### Description
**Includes 4 important algorithms - Bellman Ford Algo, Prim's Algo, Kahn's Algo, Floyd Warshall Algo  in Graph**

- [x] Fixed Bug/issues
- [x] Added algo/questions_answers/docs
- [x] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Review by rohan472000 — COMMENTED** [review]
Kindly add Wikipedia link or other sites for every algo in their respective.java files under comments.

**Comment by madm234** [comment]
> Kindly add Wikipedia link or other sites for every algo in their respective.java files under comments.

Done. Wikipedia links added at the end of each code.

**Review by rohan472000 — COMMENTED** [review]
Not at end, at top itself with other comments.

**Comment by madm234** [comment]
> Not at end, at top itself with other comments.

Done. Kindly Check

**Review by rohan472000 — COMMENTED** [review]
Put example or cases to show function working in main().

**Comment by madm234** [comment]
> Put example or cases to show function working in main().

Done. I've tried my best explaining all the examples inside main code. Tested and working fine on my side.

**Review by rohan472000 — CHANGES_REQUESTED** [review]
V and E should be renamed as vertex and edge, as viewers will understand variables easily.

**Comment by madm234** [comment]
> V and E should be renamed as vertex and edge, as viewers will understand variables easily.

Done. All V & E have been renamed to vertex and edge

**Review by rohan472000 — APPROVED** [review]

**Pull request merged**
