### PR TITLE
SieveofEratosthenes.java

### PR DESCRIPTION
**Pull request by Abdul-Azeez060**
Added SieveofEratosthenes.java

### CODE REVIEW

**Comment by rohan472000** [comment]
Provide description about this algo and link

**Comment by Abdul-Azeez060** [comment]
> Provide description about this algo and link

Yep I will provide the description, what is the link your asking about?

**Comment by rohan472000** [comment]
Wikipedia link or something other where a viewer can get full description.

**Comment by Abdul-Azeez060** [comment]
The Sieve of Eratosthenes is a method to find all prime numbers up to a given limit. 
Make a list of numbers from 2 to your limit.
Start with the first number (2) and mark it as prime.
Cross out all multiples of 2 in the list.
Move to the next unmarked number (3) and mark it as prime.
Cross out all multiples of 3 in the list.
Repeat steps 4 and 5 until you've checked numbers up to the square root of the limit.
The remaining unmarked numbers are all prime.
For example, if you want to find primes up to 30, you'll get: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]. It's an efficient way to find prime numbers.

https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

**Comment by rohan472000** [comment]
Not here my friend, in that .java file under comments.

**Comment by Abdul-Azeez060** [comment]
done

**Comment by rohan472000** [comment]
Kindly put it in a folder in repo, if not available then make one.

**Comment by rohan472000** [comment]
Thank for your contribution.

**Pull request merged**
