### PR TITLE
added segment_tree in tree

### PR DESCRIPTION
**Pull request by Dharmil03**
### Description
I have added segment tree code in trees folder and also i have added wikipedia link 

### Related/Fixes Issue
[Reference the related issue or task using its number or link.]

### Changes Made
[Briefly list the specific code changes made.]

### Screenshots (if applicable)
[Include any relevant screenshots or images here.]

- [x] Fixed Bug/issues
- [x] Added algo/questions_answers/docs
- [x] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by rohan472000** [comment]
Under comments in .java file, also explain a brief about what is segment tree.

**Comment by Dharmil03** [comment]
there is explanation about that in comments above the sub function in the code

**Comment by rohan472000** [comment]
That's for function, not about whole meaning of segment tree.

**Comment by rohan472000** [comment]
Thanks for your contribution.

**Pull request merged**
