### PR TITLE
Create concatinate_word_problem.java

### PR DESCRIPTION
**Pull request by thepremshankarsingh**
Hacktober'23
Added a trie problem

### CODE REVIEW

**Review by rohan472000 — COMMENTED** [review]
GIve the description and link of this question under comments in this .java file

**Review by rohan472000 — APPROVED** [review]

**Comment by rohan472000** [comment]
Thanks for your contribution.

**Comment by thepremshankarsingh** [comment]
But sir I am getting the excluded under the contribution . in Hacktober fest'23

**Comment by rohan472000** [comment]
> But sir I am getting the excluded under the contribution . in Hacktober fest'23

From last 2 days, this repo excluded from hacktoberfest and I'm not sure why, may be someone reported it for not merging their PRs, who knows.

**Pull request merged**
