### PR TITLE
Added Sudoku.java file

### PR DESCRIPTION
**Pull request by Abdul-Azeez060**
### Description
Added sudoku.java file and decreased the description.

### Related/Fixes Issue
[Reference the related issue or task using its number or link.]

### Changes Made
[Briefly list the specific code changes made.]

### Screenshots (if applicable)
[Include any relevant screenshots or images here.]

- [x] Fixed Bug/issues
- [x] Added algo/questions_answers/docs
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by Abdul-Azeez060** [comment]
I have decreased the description of the file.

**Comment by Abdul-Azeez060** [comment]
Thank you

**Review by rohan472000 — COMMENTED** [review]
Add more tests in main()

**Comment by Abdul-Azeez060** [comment]
Added test cases

**Review by rohan472000 — APPROVED** [review]

**Comment by rohan472000** [comment]
Thanks for your contribution.

**Pull request merged**
