### PR TITLE
Added Merge Sort to sorting.

### PR DESCRIPTION
**Pull request by amansheoran15**
## Pull Request Checkboxes and descriptions

**Title:** Merge Sort

### Description
Added merge sort code

### Related Issue
#47 

### Changes Made
Added merge sort algo

### Screenshots (if applicable)
NA

- [✅] Fixed Bug/issues 
- [ ✅] Added algo/questions_answers/docs
- [ ✅] This pull request is all my own work -- I have not plagiarized it.
- [✅ ] All filenames are in PascalCase.
- [✅ ] All functions and variable names follow Java naming conventions.
- [ ✅] All test cases have passed.
- [✅] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations

### CODE REVIEW

**Comment by rohan472000** [comment]
Kindly fill PR description template properly.

**Comment by amansheoran15** [comment]
Its my first time contributing, kindly help from where can i get the PR template as I deleted it in this PR.

**Comment by rohan472000** [comment]
see in .github/workflow

**Comment by amansheoran15** [comment]
Please check

**Review by rohan472000 — APPROVED** [review]

**Pull request merged**
