### PR TITLE
Added files to appropriate folders

### PR DESCRIPTION
**Pull request by SheetalPunyani**
Description
Added files to appropriate folders

Related/Fixes Issue #28

Changes Made:Added files to appropriate folders

- [x] Fixed Bug/issues #28
- [x] Added algo/questions_answers/docs
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All test cases have passed.
- [x]  All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### CODE REVIEW

**Comment by rohan472000** [comment]
Provide description of PR.

**Comment by SheetalPunyani** [comment]
> Provide description of PR.

description edited.

**Comment by rohan472000** [comment]
Kindly see PR template in workflows and edit description accordingly.

**Comment by SheetalPunyani** [comment]
> Kindly see PR template in workflows and edit description accordi

**Comment by SheetalPunyani** [comment]
> Kindly see PR template in workflows and edit description accordingly.

like this?

**Comment by rohan472000** [comment]
Plz make a separate PR as this has conflict which can't be rebased as multiple pr merged in last 24 hrs ..

**Pull request closed without merging**
